# Generated by Django 5.2.15 on 2026-06-22 07:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '__first__'),
        ('travel', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_label', models.CharField(choices=[('SAFE', 'Safe'), ('SUSPICIOUS', 'Suspicious'), ('DANGEROUS', 'Dangerous')], default='SAFE', max_length=15)),
                ('factors_json', models.JSONField()),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threat_assessments', to='alerts.alert')),
                ('travel_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threat_assessments', to='travel.travelsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_threatassessment',
                'ordering': ['-assessed_at'],
            },
        ),
    ]
